export enum COMMANDS {
  'EXIT' = 'EXIT',
  'INFO' = 'INFO',
  'LOGIN' = 'LOGIN',
  'BLOCK' = 'BLOCK',
  'ROOM' = 'ROOM',
  'ROOMS' = 'ROOMS',
  'JOIN' = 'JOIN',
  'KICK' = 'KICK',
  'LEAVE' = 'LEAVE',
  'LOGOUT' = 'LOGOUT',
  'MEMBER' = 'MEMBER',
  'ALL_USERS' = 'ALL_USERS',
  'CHATTERS' = 'CHATTERS',
  'PM' = 'PM',
  'IP' = 'IP',
}
